"""empty message

Revision ID: b7d1ac6ccd55
Revises: d9dbe4a2c28c
Create Date: 2023-08-14 01:18:18.037204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7d1ac6ccd55'
down_revision = 'd9dbe4a2c28c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rotation_period', sa.String(length=50), nullable=False))
        batch_op.drop_constraint('planets_rotarion_period_key', type_='unique')
        batch_op.create_unique_constraint(None, ['rotation_period'])
        batch_op.drop_column('rotarion_period')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rotarion_period', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('planets_rotarion_period_key', ['rotarion_period'])
        batch_op.drop_column('rotation_period')

    # ### end Alembic commands ###
